import { INGREDIENT_TYPES } from "store/models/ingredients";

export const recipe = {
  name: "🍜 Spicy Miso Ramen",
  amount: {
    quantity: 4,
    unit: "bowls",
    text: "4 bowls",
  },
  duration: {
    text: "10 hours",
    quantity: 10,
    unit: "hour",
  },
  tags: [],
  author: "UhKKu1yFStT2ggnAgtvrIh2D8yO2",
  ingredients: [
    {
      type: INGREDIENT_TYPES.HEADER,
      text: "Spicy Miso Tare",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "1 red bell pepper, deseeded",
      quantity: 1,
      unit: "",
      ingredient: "red bell pepper, deseeded",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "2 habanero chillies, deseeded",
      quantity: 2,
      unit: "",
      ingredient: "habanero chillies, deseeded",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "¼ a large onion, pureed in a food processor",
      quantity: 0.25,
      unit: "",
      ingredient: "a large onion, pureed in a food processor",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "2 cloves of garlic, grated/minced",
      quantity: 2,
      unit: "",
      ingredient: "cloves of garlic, grated/minced",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "One 2 inch piece of ginger, grated/minced",
      quantity: 2,
      unit: "inch",
      ingredient: "piece of ginger, grated/minced",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "560 g miso of various types (I like to blend white, red, and maybe a mugi or chunkier variant, though all white will work here)",
      quantity: 560,
      unit: "g",
      ingredient:
        "miso of various types (I like to blend white, red, and maybe a mugi or chunkier variant, though all white will work here)",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "10 g mirin",
      quantity: 10,
      unit: "g",
      ingredient: "mirin",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "30 g soy sauce",
      quantity: 30,
      unit: "g",
      ingredient: "soy sauce",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "5 g sesame oil",
      quantity: 5,
      unit: "g",
      ingredient: "sesame oil",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "14 g tahini",
      quantity: 14,
      unit: "g",
      ingredient: "tahini",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "8 g Tobanjan",
      quantity: 8,
      unit: "g",
      ingredient: "Tobanjan",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "60 g Gochujang",
      quantity: 60,
      unit: "g",
      ingredient: "Gochujang",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "1/2 tsp smoked paprika (or more to taste)",
      quantity: 0.5,
      unit: "tsp",
      ingredient: "smoked paprika (or more to taste)",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "1 tbsp togarashi (this is for flavor, we’re also adding spice to the bottom of the bowl)",
      quantity: 1,
      unit: "tbsp",
      ingredient:
        "togarashi (this is for flavor, we’re also adding spice to the bottom of the bowl)",
    },
    {
      type: INGREDIENT_TYPES.HEADER,
      text: "Spice Blend",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "4 parts ground togarashi",
      quantity: 4,
      unit: "part",
      ingredient: "ground togarashi",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "1 part ground Sansho or szechuan peppercorn",
      quantity: 1,
      unit: "part",
      ingredient: "ground Sansho or szechuan peppercorn",
    },
    {
      type: INGREDIENT_TYPES.HEADER,
      text: "Soup",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "4 lbs chicken backs, (you can sub in pork neck bones if you like the flavor, but I keep it all chicken)",
      quantity: 4,
      unit: "pound",
      ingredient:
        "chicken backs, (you can sub in pork neck bones if you like the flavor, but I keep it all chicken)",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "1 onion, split in half and skin removed",
      quantity: 1,
      unit: "",
      ingredient: "onion, split in half and skin removed",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "1 head of garlic, cut in half to expose cloves",
      quantity: 1,
      unit: "",
      ingredient: "head of garlic, cut in half to expose cloves",
    },
    {
      type: INGREDIENT_TYPES.HEADER,
      text: "Aroma Oil",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "1 cup fat of choice (I typically use pork lard or chicken fat, though vegetable oil also works here)",
      quantity: 1,
      unit: "cup",
      ingredient:
        "fat of choice (I typically use pork lard or chicken fat, though vegetable oil also works here)",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "8 cloves garlic",
      quantity: 8,
      unit: "",
      ingredient: "cloves garlic",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "2-inch piece of ginger, sliced into ¼ inch coins",
      quantity: 2,
      unit: "inch",
      ingredient: "piece of ginger, sliced into ¼ inch coins",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "½ a small onion",
      quantity: 0.5,
      unit: "",
      ingredient: "a small onion",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "3 tbsp ground togarashi",
      quantity: 3,
      unit: "tbsp",
      ingredient: "ground togarashi",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "8 chinese chilis, whole",
      quantity: 8,
      unit: "",
      ingredient: "chinese chilis, whole",
    },
    {
      type: INGREDIENT_TYPES.INGREDIENT,
      text: "2 tsp szechuan peppercorns",
      quantity: 2,
      unit: "tsp",
      ingredient: "szechuan peppercorns",
    },
  ],
  method: [],
};
