export default function wordToNumber(word) {
  switch (word) {
    case "one":
    case "One":
      return 1;
    case "two":
    case "Two":
      return 2;
    case "three":
    case "Three":
      return 3;
    case "four":
    case "Four":
      return 4;
    case "five":
    case "Five":
      return 5;
    case "six":
    case "Six":
      return 6;
    case "seven":
    case "Seven":
      return 7;
    case "eight":
    case "Eight":
      return 8;
    case "nine":
    case "Nine":
      return 9;
    case "ten":
    case "Ten":
      return 10;
    case "eleven":
    case "Eleven":
      return 11;
    case "twelve":
    case "Twelve":
      return 12;
    case "thirteen":
    case "Thirteen":
      return 13;
    case "fourteen":
    case "Fourteen":
      return 14;
    case "fifteen":
    case "Fifteen":
      return 15;
    case "sixteen":
    case "Sixteen":
      return 16;
    case "seventeen":
    case "Seventeen":
      return 17;
    case "eighteen":
    case "Eighteen":
      return 18;
    case "nineteen":
    case "Nineteen":
      return 19;
    case "twenty":
    case "Twenty":
      return 20;
  }
}
